/* Vtable */
"__vt__Q43scn4step4hero11AbilityBase" = 0x807b3640;

/* other shit */
"__ct__Q43scn4step4hero11AbilityBaseFRQ33scn4step9ComponentRQ43scn4step4hero4Hero" = 0x804cfed0;
"__dt__Q43scn4step4hero11AbilityBaseFv" = 0x804cfee8;

"setup__Q43scn4step4hero11AbilityBaseFv" = 0x804cfeec;
"tryToChangeStateOnCarry__Q43scn4step4hero11AbilityBaseFv" = 0x804cfef0;
"tryToChangeStateOnInterval__Q43scn4step4hero11AbilityBaseFv" = 0x804cfef4;
"tryToChangeStateOnDamage__Q43scn4step4hero11AbilityBaseFv" = 0x804cfef8;
"tryToChangeState__Q43scn4step4hero11AbilityBaseFv" = 0x804d00a0;