"__vt__Q43scn4step4hero9StateBase" = 0x807b68b0;

"__ct__Q43scn4step4hero9StateBaseFPQ43scn4step4hero4Hero" = 0x8050c024;
"__dt__Q43scn4step4hero9StateBaseFv" = 0x8050c050;

"procAnim__Q43scn4step4hero9StateBaseFv" = 0x8050c038;
"procConstraint__Q43scn4step4hero9StateBaseFv" = 0x8050c040;
"procEnd__Q43scn4step4hero9StateBaseFv" = 0x8050c04c;
"procFixPos__Q43scn4step4hero9StateBaseFv" = 0x8050c044;
"procMove__Q43scn4step4hero9StateBaseFv" = 0x8050c03c;
"procObjCollReact__Q43scn4step4hero9StateBaseFv" = 0x8050c048;